### ISSUE TITLE
json export no work now

### ISSUE THREAD

**Issue by demonzla** [zkxs/ExportNeosToJson#2]
plugin no work, error in log:

23:48:50.577 ( 60 FPS)	Unsupported export format: json, supported formats: 
	ID: collada	Ext: dae	Info: COLLADA - Digital Asset Exchange Schema
	ID: x	Ext: x	Info: X Files
	ID: stp	Ext: stp	Info: Step Files
	ID: obj	Ext: obj	Info: Wavefront OBJ format
	ID: objnomtl	Ext: obj	Info: Wavefront OBJ format without material file
	ID: stl	Ext: stl	Info: Stereolithography
	ID: stlb	Ext: stl	Info: Stereolithography (binary)
	ID: ply	Ext: ply	Info: Stanford Polygon Library
	ID: plyb	Ext: ply	Info: Stanford Polygon Library (binary)
	ID: 3ds	Ext: 3ds	Info: Autodesk 3DS (legacy)
	ID: gltf2	Ext: gltf	Info: GL Transmission Format v. 2
	ID: glb2	Ext: glb	Info: GL Transmission Format v. 2 (binary)
	ID: gltf	Ext: gltf	Info: GL Transmission Format
	ID: glb	Ext: glb	Info: GL Transmission Format (binary)
	ID: assbin	Ext: assbin	Info: Assimp Binary File
	ID: assxml	Ext: assxml	Info: Assimp XML Document
	ID: x3d	Ext: x3d	Info: Extensible 3D
	ID: fbx	Ext: fbx	Info: Autodesk FBX (binary)
	ID: fbxa	Ext: fbx	Info: Autodesk FBX (ascii)
	ID: m3d	Ext: m3d	Info: Model 3D (binary)
	ID: m3da	Ext: a3d	Info: Model 3D (ascii)
	ID: 3mf	Ext: 3mf	Info: The 3MF-File-Format
	ID: pbrt	Ext: pbrt	Info: pbrt-v4 scene description file
	ID: assjson	Ext: json	Info: Assimp JSON Document

**Comment by zkxs** [comment]
Thanks for the report. This should be fixed now in [version 1.1.1](https://github.com/zkxs/ExportNeosToJson/releases/tag/1.1.1.0)
